source 'https://rubygems.org'
gem 'rails', '4.2.5'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
# gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'responders'

group :doc do
  gem 'sdoc', '~> 0.4.0', group: :doc
end

group :development, :test do
  gem 'pry'
  gem 'pry-doc', '>= 0.6.0'
  gem 'pry-byebug'
  gem 'method_source', '>= 0.8.2'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'guard'
  gem 'guard-minitest'
  gem 'foreman'
end

group :test do
  gem 'minitest-rails'
  gem 'minitest-reporters'
end
